name: Figma

on: 
  workflow_dispatch:
    inputs: 
      file_id:
        description: 'Figma file ID'
        required: true
      figma_token:
        description: 'Figma API token'
        required: true
      style_dictionary_url: 
        description: 'Style Dictionary URL'
        required: true

jobs:
  add-collection-to-figma:
    # Prevents changesets action from creating a PR on forks
    if: github.repository == 'RedHat-UX/red-hat-design-tokens'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: brianferry/figma-create@v1.0
        with:
          api_token: ${{ github.event.inputs.figma_token }}
          file_id: ${{ github.event.inputs.file_id }}
          style_dictionary_url: ${{ github.event.inputs.style_dictionary_url }}
      - name: Archive Figma Tokens Payload
        uses: actions/upload-artifact@v4
        with:
          name: figma-tokens
          path: build/
