name: Figma

on: workflow_dispatch

jobs:
  add-collection-to-figma:
    # Prevents changesets action from creating a PR on forks
    if: github.repository == 'RedHat-UX/red-hat-design-tokens'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: npm
        env:
          api_token: ${{ secrets.FIGMA_API_TOKEN }}
          file_id: ${{ secrets.FIGMA_FILE_ID }}

      # Set up GitHub Actions caching for Wireit.
      - uses: google/wireit@setup-github-actions-caching/v1

      - run: npm ci --prefer-offline
      - run: npm run figma -- $api_token $file_id
