name: Figma

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - auto_merge_enabled
  push:
    branches:
      - main

jobs:
  add-collection-to-figma:
    # Prevents changesets action from creating a PR on forks
    if: github.repository == 'RedHat-UX/red-hat-design-tokens'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: npm

      # Set up GitHub Actions caching for Wireit.
      - uses: google/wireit@setup-github-actions-caching/v1

      - run: npm ci --prefer-offline
      - run: npm run figma
