name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    # Prevents changesets action from creating a PR on forks
    if: github.repository == 'RedHat-UX/red-hat-design-tokens'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      # Set up GitHub Actions caching for Wireit.
      - uses: google/wireit@setup-github-actions-caching/v1

      - run: npm ci --prefer-offline
      - run: npm run package # also builds and tests

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npx changeset publish
          commit: "chore: version package"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # changesets action outputs `publishedPackages` in the format
      #   [{"name": "@xx/xx", "version": "1.2.0"}, {"name": "@xx/xy", "version": "0.8.9"}]
      # The following step converts that list of objects to a list of strings (git tags for github releases)
      # and joins them with commas, for consumption in the next step
      #   "@xx/xx@1.2.0, @xx/xy@0.8.9"
      - name: Transform Tags
        id: get-tags
        if: ${{ steps.changesets.outputs.published == 'true' }}
        run: |
          tags=$( echo '${{ steps.changesets.outputs.publishedPackages }}' | jq -c 'map([.name,.version]) | map(join("@")) | join(", ")' )
          echo "$tags"
          echo "::set-output name=tags::$tags"

      - name: Upload release artifact
        uses: actions/github-script@v6
        if: ${{ steps.changesets.outputs.published == 'true' }}
        with:
          debug: ${{ secrets.ACTIONS_RUNNER_DEBUG }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const workspace = '${{ github.workspace }}';
            const tags = ${{ steps.get-tags.outputs.tags }}.split(',');
            const { release } = await import('${{ github.workspace }}/lib/release.js');
            await release({ core, github, tags, workspace });

      - name: Publish VSCode
        if: ${{ steps.changesets.outputs.published == 'true' }}
        run: |
          cd editor/vscode
          npx vsce --publish --pre-release
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
